# Scala CircleCI 2.0 configuration file
#

job_defaults: &job_defaults
  docker:
  - image: circleci/openjdk:8-jdk

  working_directory: ~/repo

  environment:
    # Customize the JVM maximum heap limit
    JVM_OPTS: -Xmx3200m

commands:
  restore_cache: &restore_cache
    keys:
    - v1-dependencies-{{ checksum "build.gradle" }}
    # fallback to using the latest cache if no exact match is found
    - v1-dependencies-

  save_cache: &save_cache
    paths:
    - ~/.gradle
    key: v1-dependencies--{{ checksum "build.gradle" }}

  save_test_results: &save_test_results
    name: Save test results
    command: |
      mkdir -p ~/test-results/junit/
      find . -type f -regex ".*/build/test-results/.*xml" -exec cp {} ~/test-results/junit/ \;
    when: always

  store_test_results: &store_test_results
    path: ~/test-results

  store_artifacts: &store_artifacts
    path: ~/test-results/junit

version: 2

jobs:
  build:
    <<: *job_defaults
    steps:
    - checkout
    - restore_cache: *restore_cache
    - save_cache: *save_cache
    - run: gradle test
    - run: *save_test_results
    - store_test_results: *store_test_results
    - store_artifacts: *store_artifacts

  integration_test_18060ce:
    <<: *job_defaults
    steps:
    - checkout
    - restore_cache: *restore_cache
    - save_cache: *save_cache
    - setup_remote_docker:
        version: 18.06.0-ce
        docker_layer_caching: true
    - run: gradle integrationTest
    - run: *save_test_results
    - store_test_results: *store_test_results
    - store_artifacts: *store_artifacts

  integration_test_17030ce:
    <<: *job_defaults
    steps:
    - checkout
    - restore_cache: *restore_cache
    - save_cache: *save_cache
    - setup_remote_docker:
        version: 17.03.0-ce
        docker_layer_caching: true
    - run: gradle integrationTest
    - run: *save_test_results
    - store_test_results: *store_test_results
    - store_artifacts: *store_artifacts

workflows:
  version: 2
  workflow:
    jobs:
    - build
    - integration_test_17030ce:
        requires:
        - build
    - integration_test_18060ce:
        requires:
        - build